describe('Full site functionality test', function() {
    it('should look amazing navigating from the landing page to the results page', function() {
        cy.visit('http://localhost:3030')
        cy.scrollTo('top', {duration: 500})
        cy.wait(200)
        cy.get('.it-search-input').type('78745')
        cy.scrollTo('top', {duration: 500})
        cy.wait(500)
    })
    it('should look amazing filtering the results page', function() {
        cy.get('.it-cta-form > :nth-child(3)').click()
        cy.scrollTo('top', {duration: 500})
        cy.wait(500)
        cy.get(':nth-child(1) > .dropdown-toggle').click()
        cy.wait(500)
        cy.get('[data-value="space"]').click()
        cy.scrollTo('top', {duration: 500})
        cy.wait(500)
        cy.get(':nth-child(2) > .dropdown-toggle').click()
        cy.wait(500)
        cy.get('.show.dropdown > .dropdown-menu > [data-value="1"]')
        cy.wait(500)
        cy.get('[data-value="1"]').click()
        cy.scrollTo('top', {duration: 500})
        cy.wait(500)
        cy.get(':nth-child(3) > .dropdown-toggle').click()
        cy.wait(250)
        cy.get('.results-btn.show > .dropdown-menu > [data-value="1"]').click()
        cy.get(':nth-child(4) > .dropdown-toggle').click()
        cy.get('.results-btn.show > .dropdown-menu > [data-value="1"]').click()
        cy.scrollTo('top', {duration: 500})
        cy.wait(1000)
        cy.get('[data-filter="easeOfAccess"]').click()
        cy.wait(250)
        cy.get('[data-filter="duration"]').click()
        cy.wait(250)
        cy.get('[data-filter="type"]').click()
        cy.wait(1000)
        cy.get(':nth-child(1) > .thumbnail-button').click()
        cy.scrollTo('top', {duration: 500})
    })
    it('should display an amazing product page', function() {
        cy.get(':nth-child(2) > .form-control').type('Mark Fuechec')
        cy.wait(250)
        cy.get('form > :nth-child(3) > .form-control').type('fuechec.mark@gmail.com')
        cy.wait(250)
        cy.get(':nth-child(4) > .form-control').type('5129719303')
        cy.wait(500)
        cy.get(':nth-child(1) > .DayPickerInput > input').click()
        cy.wait(1000)
        cy.scrollTo('top', {duration: 500})
        cy.wait(500)
        cy.get('[style="border-right: 1px solid rgb(53, 59, 64);"] > .listingPicture').click()
        cy.wait(250)
        cy.get('.carousel-control-next-icon').click()
        cy.wait(500)
        cy.get('.carousel-control-next-icon').click()
        cy.wait(500)
        cy.get('.carousel-control-prev-icon').click()
        cy.wait(250)
    })
    it('should look amazing posting a new item or property', function() {
        cy.visit('http://localhost:3030/post')
        cy.wait(1000)
        cy.get('#postPropertyImage').click()
        cy.scrollTo('top', {duration: 500})
        cy.wait(500)
        cy.get(':nth-child(1) > .btn').click()
        cy.wait(250)
        cy.get('#postItemImage').click()
        cy.scrollTo('top', {duration: 500})
        cy.wait(250)
        cy.get('#validationCustom01').type('Mark Fuechec')
        cy.wait(250)
        cy.get('#validationCustom02').type('teamalcove@gmail.com')
        cy.wait(250)
        cy.get('#validationCustom03').type('512 971 9303')
        cy.wait(500)
        cy.get(':nth-child(2) > .custom-control-label').click()
        cy.wait(100)
        cy.get(':nth-child(3) > .custom-control-label').click()
        cy.wait(100)
        cy.get(':nth-child(2) > .custom-control-label').click()
        cy.wait(200)
        cy.get('#validationCustom04').type('78745')
        cy.get(':nth-child(4) > .step2Input > .form-control').type('100000')
        cy.wait(500)
        cy.get(':nth-child(2) > .btn').click()
        cy.wait(500)
        cy.scrollTo('top', {duration: 500})
        cy.get(':nth-child(1) > :nth-child(2) > [data-value="1"]').click()
        cy.wait(100)
        cy.get(':nth-child(1) > :nth-child(2) > [data-value="4"]').click()
        cy.wait(100)
        cy.get(':nth-child(4) > .tsDropdownWrapper > [data-value="2"]').click()
        cy.wait(100)
        cy.get(':nth-child(5) > .tsDropdownWrapper > [data-value="4"]').click()
        cy.wait(500)
        cy.get('[style="height: 2rem;"]').click()
        cy.scrollTo('top', {duration: 500})
        cy.wait(500)
        cy.get('[style="margin-top: 4rem;"] > :nth-child(2) > .btn').click()
        cy.scrollTo('top', {duration: 500})
        cy.wait(1000)
        cy.get('#postTitle').type('Team Alcove made this')
        cy.get('#postDescription').type('Built by: Tom Chandler, Jonathan Diaz, Bruce Ferguson III, Mark Fuechec, Natalia Malesa, Kytra Murphree, Tim Sanderson, Ish Tahir')
        cy.scrollTo('top', {duration: 500})
        cy.wait(2000)
        cy.get('#openPreviewButton').click()
        cy.get('.modal').scrollTo('bottom', {duration: 1500})
        cy.get(':nth-child(1) > :nth-child(1) > :nth-child(1) > h4').scrollIntoView({duration: 1000})
        cy.get(':nth-child(2) > .form-control').type('Future Employer')
        cy.get(':nth-child(3) > .form-control').type('boss@somewheregood.biz')
        cy.get(':nth-child(4) > .form-control').type('555555555')
        cy.get(':nth-child(1) > :nth-child(1) > :nth-child(1) > h4').scrollIntoView({duration: 750})
        cy.wait(500)
        cy.scrollTo('bottom', {duration: 1000})
        cy.get('.modal-footer > :nth-child(2)').click()
        cy.scrollTo('top', {duration: 1000})
        cy.wait(1000)
        cy.get(':nth-child(2) > .active').click()
        cy.scrollTo('bottom')
        cy.get('.it-footer-logo').click()
    })
})